config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events
  resources :comments
  resources :friendships
  resources :boards
  resources :items
  resources :event_items
  resources :contributions
  resources :sessions, :only => [:new, :create, :destroy]
  get "users/:id/events", to: 'users#events', as: 'user_events'
  get "boards/:id/board", to: 'boards#user', as: 'user_boards'
  get "contributions/:id/new/:item_id", to: 'contributions#new', as: 'event_contribution'
  get '/signup' => 'users#index'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :contributions
	has_many :events, :through => :contributions
	has_many :comments
	has_many :events, :through => :comments
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :boards
	has_many :events
	attr_accessor :password, :password_confirmation
	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :first_name, :last_name, :presence => true
	validates :email, :uniqueness => true, :format => { :with => email_regex }
	validates :password, :password_confirmation, :presence => true

	before_save :encrypt_password

	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	private
		def encrypt_password
			self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
			self.encrypted_password = encrypt(self.password)
		end

		def encrypt(pass)
			Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.new
  end
  def events
    @events = Event.where(user_id: params[:id])
    @user = User.find(params[:id])
  end
  def show
  	@user = User.find(session[:user_id])
    # show events only from YOUR friends
    @events = Event.all
    users = User.where('id != ?', session[:user_id])
    @friends = User.find(session[:user_id]).friends
    @not_friends = users - @friends
    @friendship = Friendship.new
    @my_events = Event.where(:user_id => @user)
    @events = Event.where(:user_id => @friends)
    @eventitems = EventItem.all
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "User successfully created"
  		redirect_to '/'
  	else

  	end
  end

  def destroy
    sign_out
    redirect_to user
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/events.html.erb
<div class='container'>
	<div class='row'>
		<p><%= link_to("Back to Dashboard", user_path(@user.id)) %></p>
		<h2><%= @user.first_name %>'s Events</h2>
		<table class='table table-striped'>
			<thead>
				<th>Name</th>
				<th>Deadline</th>
			</thead>
			<tbody>
				<% @events.each do |event| %>
					<tr>
						<td><%= event.event_name %></td>
						<td><%= event.deadline %></td>
					</tr>

				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/index.html.erb
<div class='container registration_page'>
	<div class='row register'>
		<div class='col-md-4'>
			<h2>Register</h2>
			<p id="notice"><%= notice %></p>
			<%= simple_form_for @user do |f| %>
			<%= f.input :first_name %>
			<%= f.input :last_name %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.input :password_confirmation %>
			<%= f.submit "Create user", :class => "btn btn-md btn-primary" %>
			<% end %>
		</div>
	</div>
	<div class='row register'>
		<p>Already a user?<%= link_to("Login", signin_path) %> here</p>
	</div>
</div>

app/views/users/new.html.erb
<div class='container registration_page'>
	<nav class='navbar my_nav navbar-default'>
			<h2>Giver</h2>
			
		</nav>
	<div class='row register'>
		<div class='col-md-4'>
			<h2>Register</h2>
			<p id="notice"><%= notice %></p>
			<%= simple_form_for @user do |f| %>
			<%= f.input :first_name %>
			<%= f.input :last_name %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.input :password_confirmation %>
			<%= f.submit "Create user", :class => "btn btn-md btn-primary" %>
			<% end %>
		</div>
	</div>
	<div class='row register'>
		<p>Already a user?<%= link_to("Login", signin_path) %> here</p>
	</div>
</div>

app/views/users/show.html.erb
<div class='container'>
	<div class='my_nav'>
		<p class='name'>Welcome <%= @user.first_name %></p>
		<p class='text-right'><%= link_to("Log off", signout_path) %></p>
		<!-- <p class='text-right'><%= link_to("Friends", friendship_path(@user.id))%></p> -->
	</div>
	<div class='row'>
		<div class='col-md-3 board text-center'>
			<h2><%= link_to("My Boards", boards_path) %></h2>
		</div>
		<div class='col-md-4 board text-center'>
			<h2><%= link_to("My Contributions", contribution_path(@user.id)) %></h2>
		</div>
		<div class='col-md-4 board text-center'>
			<h2><%= link_to("Create Board", new_board_path) %></h2>
		</div>
		
	</div>
</div>
<div class='container show'>
	<div class='row'>
	</div>
	<div class='row'>
		<div class='col-md-4'>
			<h2>My Friends</h2>
			<table class='table table-striped'>
				<% @friends.each do |person| %>
					<tr>
						<td><%= person.first_name %> <%= person.last_name %></td>
						<td><%= link_to("Events", user_events_path(person.id))%></td>
						<td><%= link_to("Boards", user_boards_path(person.id))%></td>
						<td><%= simple_form_for @friendship, :url => friendship_path, :method => :delete do |f| %>
							<%= f.input :user_id, :as => :hidden, :input_html => {:value => @user.id} %>
							<%= f.input :friend_id, :as => :hidden, :input_html => {:value => person.id} %>
							<%= f.submit "Remove Friend", :class => "btn btn-sm btn-primary" %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
		<div class='col-md-5'></div>
		<div class='col-md-4'>
			<h2>Upcoming Events</h2>
			<!-- <p id="success"><%= flash[:success] %></p> -->
			<table class='table table-striped'>
				<thead>
					<th>Event</th>
					<th>Owner</th>
					<th>Deadline</th>
				</thead>
				<tbody>
					<tr>
						<td><%= link_to("Create Event", new_event_path) %></td>
						
					</tr>
					<% @my_events.each do |event| %>
						<tr>
							<td><a href="/events/<%= event.id %>"><%= event.event_name %></a></td>
							<td><%= event.user.first_name %></td>
							<td><%= event.deadline %></td>
							<td><% if event.user.id == @user.id %>
								<%= link_to "Cancel", event_path(event.id), method: :delete %>
								<% end %>
							</td>
						</tr>
					<% end %>
					<% @events.each do |event| %>
						<tr>
							<td><a href="/events/<%= event.id %>"><%= event.event_name %></a></td>
							<td><%= event.user.first_name %></td>
							<td><%= event.deadline %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class='col-md-3'>
			<h2>My Not Yet Friends</h2>
			<table class='table table-striped'>
				<% @not_friends.each do |user| %>
					<tr>
						<td><%= user.first_name %> <%= user.last_name %></td>
						<td><%= link_to("Events", user_events_path(user.id))%></td>
						<td><%= link_to("Boards", user_boards_path(user.id))%></td>
						<td><%= simple_form_for @friendship do |f| %>
							<%= f.input :user_id, :as => :hidden, :input_html => {:value => @user.id} %>
							<%= f.input :friend_id, :as => :hidden, :input_html => {:value => user.id} %>
							<%= f.submit "Add Friend", :class => "btn btn-sm btn-primary" %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
	<!-- <div class='row'> -->
		<!-- <div class='col-md-8'></div> -->
		
	<!-- </div> -->
</div>
<!-- <div class='container'>
	<% if !@my_events.nil? %>
	<div class='col-md-3 item_board text-center'>
		<% @my_events.each do |event| %>
			<p><a href="/events/<%= event.id %>"><%= event.event_name %></a></p>
			
				
			
			<p><%= event.user.first_name %></p>
			<p><%= event.description %></p>
			<p><%= event.deadline %></p>
			<p><% if event.user.id == @user.id %>
				<%= link_to "Cancel My Event", event_path(event.id), method: :delete %>
				<% end %>
			</p>
		<% end %>
	</div>
	<% end %>
	<% if !@events.nil? %>
	<div class='col-md-3 item_board text-center'>
		<% @events.each do |event| %>
			
				<p><a href="/events/<%= event.id %>"><%= event.event_name %></a></p>
				<p><%= event.user.first_name %></p>
				<p><%= event.description %></p>
				<p><%= event.deadline %></p>
			
		<% end %>
	</div>
	<% end %>
	
</div> -->