config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events
  resources :comments
  resources :friendships
  resources :boards
  resources :items
  resources :event_items
  resources :contributions
  resources :sessions, :only => [:new, :create, :destroy]
  get "users/:id/events", to: 'users#events', as: 'user_events'
  get "boards/:id/board", to: 'boards#user', as: 'user_boards'
  get "contributions/:id/new/:item_id", to: 'contributions#new', as: 'event_contribution'
  get '/signup' => 'users#index'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  root 'users#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :contributions
  has_many :users, :through => :contributions
  has_many :comments
  has_many :users, :through => :comments
  has_many :event_items
  has_many :items, :through => :event_items
  attr_accessor :year, :month, :day
  validates :event_name, :description, :user, :presence => true
  validates :deadline, :presence => true
  validate :deadline_must_be_future

  def deadline_must_be_future
    errors.add(:deadline, "can't be in the past") if
      !deadline.blank? and deadline < Date.today
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
	end

	def show
		@user = User.find(session[:user_id])
		@event = Event.find(params[:id])
		@date = (Date.parse(@event.deadline) - Date.today).to_s
		@date.slice! "/1"
		@comments = Comment.where(event_id: params[:id])
		@comment = Comment.new
		@contributions = Contribution.where(event_id: @event)
		@event_contributions = 0
		@contributions.each do |contribution| 
			@event_contributions = contribution.amount + @event_contributions
		end
	end

	def new
		@user = User.find(session[:user_id])
		@event = Event.new
	end

	def create
		@event = Event.new(event_name: event_params[:event_name], description: event_params[:description], deadline: deadline_params, user_id: session[:user_id])
		if @event.save
			flash[:success] = "Event successfully created"
			redirect_to user_path(session[:user_id])
		else
			flash[:notice] = "Please make sure you fill in all fields and event is after today"
			redirect_to new_event_path
		end
	end

	def destroy
		# in addition to destroying the event, we must also destroy all EventItems
		##related to that event, along with comments, and contributions
		
		#SO 1. Events, 2. EventItems, 3. Contributions, 4. Comments

		# also, there should probably be an JS alert going off when someone presses
		##the delete button, you know, to confirm??
		puts "Event id: \n\n\n\n\n\n"
		puts params
		puts "\n\n\n\n\n\n"
			# destroy the event
		Event.find(params[:id]).destroy
			#destroy the event items
		eventitem = EventItem.where(event_id: params[:id])
		EventItem.find(eventitem[0].id).destroy
			#destroy the contributions
		Contribution.where(event_id: params[:id]).destroy_all
			#destroy the comments
		Comment.where(event_id: params[:id]).destroy_all
		redirect_to user_path(session[:user_id])
		
	end
		

	private
		def event_params
			params.require(:event).permit(:event_name, :description, :day, :month, :year)
		end
		def deadline_params
			require 'date'	
			Date.parse(event_params[:month].to_s + " " + event_params[:day].to_s, ", " + event_params[:year].to_s)
		end
end

app/helpers/events_helper.rb
module EventsHelper
	def months 
		['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
	end

end

app/views/events/new.html.erb
<div class='container'>
	<div class='col-md-4'>
		<p><%= link_to("Back to Dashboard", user_path(@user.id)) %></p>
		<h2>Create Event</h2>
		<p id="success"><%= flash[:notice] %></p>
		<%= simple_form_for @event do |f| %>
		<%= f.input :event_name %>
		<%= f.input :description %>
		<%= f.input :month, collection: months, prompt: "Month" %>
		<%= f.input :day, collection: 1..31, prompt: "Day" %>
		<%= f.input :year, collection: 2015..2020, prompt: "Year" %>
		<%= f.submit "Create Event" %>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<div class='container show'>
	<div class='row'>
		<p><%= link_to("Back to Dashboard", user_path(@user.id)) %></p>
		<h1 class='text-center'><%= @event.user.first_name %> <%= @event.user.last_name %></h1>
		<h2 class='text-center'><%= @event.event_name %></h2>
		<!-- <p class='text-center'><%= @event.description %></p> -->
		<p class='text-center'>Deadline: <%= @event.deadline %></p>
		<p class='text-center'>Time remaining: <%= @date %> days</p>
	</div>
	<div class='row'>
		<div class='col-md-4'>
			<h3>Discussion Board</h3>
			<table class='table table-striped'>
				<thead>
					<th>User</th>
					<th>Comment</th>
				</thead>
				<tbody>
					<% @comments.each do |comment| %>
						<tr>
							<td><%= comment.user.first_name %> <%= comment.user.last_name %></td>
							<td><%= comment.content %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<h4>Add Comment</h4>
			<%= simple_form_for @comment do |f| %>
			<%= f.input :content %>
			<%= f.input :event_id, :as => :hidden, :input_html => {:value => @event.id} %>
			<%= f.submit "Create" %>
			<% end %>
		</div>
		<div class='col-md-7 event_board text-center'>
			<h3><%= @event.user.first_name%>'s Wishlist</h3>
			<% @event.items.each do |event| %>
				<p><%= @event.user.first_name %> is hoping for a <%= event.item_name %></p>
				<p><%= @event.user.first_name %> has received $<%= @event_contributions %>.00 so far</p>
				<p>It costs $<%= event.total_price %>.00</p>
				<p><%= link_to("Pitch In?", event_contribution_path(@event.id, event.id)) %>
				<p><%= image_tag event.photo.url(:medium) %></p>
			<% end %>
		</div>
		
	</div>
</div>