config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events
  resources :comments
  resources :friendships
  resources :boards
  resources :items
  resources :event_items
  resources :contributions
  resources :sessions, :only => [:new, :create, :destroy]
  get "users/:id/events", to: 'users#events', as: 'user_events'
  get "boards/:id/board", to: 'boards#user', as: 'user_boards'
  get "contributions/:id/new/:item_id", to: 'contributions#new', as: 'event_contribution'
  get '/signup' => 'users#index'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  root 'users#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :items
  validates :board_name, :presence => true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
		@boards = Board.where(user_id: session[:user_id])
		@user = User.find(session[:user_id])
	end

	def user
		@boards = Board.where(user_id: params[:id])
		@user = User.find(params[:id])
	end

	def show
		@board = Board.find(params[:id])
		@items = Item.where(board_id: @board.id)
		@item = Item.new
		@events = Event.where(user_id: session[:user_id])
		@items = Item.where(board_id: params[:id])
		@event_item = EventItem.new
	end

	def new
		@board = Board.new
		@user = User.find(session[:user_id])
	end

	def create
		@board = Board.create(board_name: board_params[:board_name], user_id: session[:user_id])
		if @board.save
			flash[:success] = "Board created"
			# redirect_to user_path(session[:user_id])
			redirect_to boards_path
		else
			flash[:notice] = "Try again"
			redirect_to new_board_path
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private
		def board_params
			params.require(:board).permit(:board_name)
		end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<div class='container'>
	<div class='row'>
		<p><%= link_to("Back to dashboard", user_path(@user.id)) %></p>
		<% @boards.each do |board| %>
		<div class='col-md-3 board text-center'>
			<h4><%= link_to(board.board_name, board_path(board.id)) %></h4>
		</div>
		<% end %>
	</div>
</div>

app/views/boards/new.html.erb
<div class='container'>
	<div class='col-md-4'>
		<p><%= link_to("Back to dashboard", user_path(@user.id)) %></p>
		<h2>Create Board</h2>
		<%= simple_form_for @board do |f| %>
		<%= f.input :board_name %>
		<%= f.submit "Create Board" %>
		<% end %>
	</div>
</div>

app/views/boards/show.html.erb
<div class='container'>
	<div class='row'>
		<p><%= link_to("Back to my boards", boards_path) %></p>
		<% @items.each do |item| %>
			<div class='col-md-3 item_board text-center'>
				<h5><%= item.item_name %></h5>
				<h5>$<%= item.total_price %>.00</h5>
				<p><%= image_tag item.photo.url(:medium) %></p>
				<p><%= link_to("Remove Item", item_path(item.id), method: :delete)%></p>
			</div>		
		<% end %>
		
	</div>
</div>
<div class='container show'>
	<div class='row'>
		<div class='col-md-4'>
			<h3>Add Item to Board</h3>
			<p><%= notice %></p>
			<%= simple_form_for @item, :html => { :multipart => true } do |f| %>
			<%= f.input :board_id, :as => :hidden, :input_html => {:value => @board.id} %>
			<%= f.input :item_name %>
			<%= f.input :total_price %>
			<%= f.file_field :photo %>
			<%= f.submit 'Add to board', :class => "btn btn-md btn-primary" %>
			<% end %>
		</div>
		<div class='col-md-4'></div>
		<div class='col-md-4'>
			<h3>Add Item to Event</h3>
			<p><%= notice %></p>
			<%= simple_form_for @event_item do |f| %>
			<%= f.input :board, :as => :hidden, :input_html => {:value => @board.id}%>
			<%= f.association :item, :collection => @items, :label_method => :item_name, :value_method => :id, :label => "Item" , :include_blank => false %>
			<%= f.association :event, :collection => @events, :label_method => :event_name, :value_method => :id, :label => "Event" , :include_blank => false %>
			<%= f.submit "Add Item", :class => "btn btn-md btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/boards/user.html.erb
<div class='container'>
	<div class='row'>
		<p><%= link_to("Back to dashboard", user_path(@user.id)) %></p>
		<% @boards.each do |board| %>
		<div class='col-md-3 board text-center'>
			<h4><%= link_to(board.board_name, board_path(board.id)) %></h4>
		</div>
		<% end %>
	</div>
</div>